FROM python:3.12.8-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/workspace/backend

WORKDIR /workspace/backend

RUN pip install --no-cache-dir confluent-kafka==2.6.1

COPY backend/app ./app

CMD ["python", "-m", "app.mes_mock"]
