MERGE (:Area {area_id:'Photo', area_name:'Photolithography'});
MERGE (:Area {area_id:'Etch', area_name:'Dry Etch'});
MERGE (r:Recipe {recipe_id:'RECIPE01', recipe_name:'CT-EXP-45NM'});
MERGE (r:Recipe {recipe_id:'RECIPE03', recipe_name:'CT-EXP-40NM'});
MERGE (r:Recipe {recipe_id:'RECIPE02', recipe_name:'CT-ETCH-45NM'});
MERGE (r:Recipe {recipe_id:'RECIPE04', recipe_name:'CT-ETCH-40NM'});
MERGE (rs:RecipeStep {recipe_id:'RECIPE01', recipe_step_no:1}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE01'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-cdd155dfdc189254606b'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE01', recipe_step_no:2}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE01'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-3ccf406ae28711c00879'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE03', recipe_step_no:1}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE03'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-0a3a7a4813a97b959307'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE03', recipe_step_no:2}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE03'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-2716733d867b9759de0e'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE02', recipe_step_no:1}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE02'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-690075e98afb0613b8bb'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE02', recipe_step_no:2}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE02'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-2eb21fd1533d5a36e3bb'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE04', recipe_step_no:1}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE04'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-50b47aac3659abaf103a'}]->(r);
MERGE (rs:RecipeStep {recipe_id:'RECIPE04', recipe_step_no:2}) WITH rs MATCH (r:Recipe {recipe_id:'RECIPE04'}) MERGE (rs)-[:STEP_OF {relation_id:'REL-338f14a7da8e648bd28b'}]->(r);
MERGE (s:ProcessStep {step_id:'CT-PHOTO', step_seq:1}) WITH s MATCH (a:Area {area_id:'Photo'}) MERGE (s)-[:IN_AREA {relation_id:'REL-396394b56797636804b3'}]->(a);
MERGE (s:ProcessStep {step_id:'CT-ETCH', step_seq:2}) WITH s MATCH (a:Area {area_id:'Etch'}) MERGE (s)-[:IN_AREA {relation_id:'REL-195741388b2bfa2b2ebc'}]->(a);
MATCH (p:ProcessStep {step_id:'CT-PHOTO'}),(n:ProcessStep {step_id:'CT-ETCH'}) MERGE (p)-[:NEXT_STEP {relation_id:'REL-02c877314abc4f84f39d'}]->(n);
MERGE (m:EquipmentModel {model_code:'PH-9000', model_name:'Photo Scanner'}) WITH m MATCH (a:Area {area_id:'Photo'}) MERGE (m)-[:IN_AREA {relation_id:'REL-9ae2117622f441370518'}]->(a);
MERGE (m:EquipmentModel {model_code:'ET-7500', model_name:'Dry Etcher'}) WITH m MATCH (a:Area {area_id:'Etch'}) MERGE (m)-[:IN_AREA {relation_id:'REL-7d135c28da6ef444f2a8'}]->(a);
MERGE (e:Equipment {equipment_id:'EQP01'}) SET e.area='Photo', e.model_code='PH-9000' WITH e MATCH (m:EquipmentModel {model_code:'PH-9000'}) MERGE (e)-[:OF_MODEL {relation_id:'REL-939dd36634df593cbd27'}]->(m);
MATCH (e:Equipment {equipment_id:'EQP01'}),(s:ProcessStep {step_id:'CT-PHOTO'}) MERGE (e)-[:PERFORMS {relation_id:'REL-37afa7aa83316d29b4d5'}]->(s);
MERGE (c:Chamber {chamber_id:'EQP01-PM1'}) WITH c MATCH (e:Equipment {equipment_id:'EQP01'}) MERGE (c)-[:PART_OF {relation_id:'REL-83f00f4fb4f6ed30f55d'}]->(e);
MERGE (c:Chamber {chamber_id:'EQP01-PM2'}) WITH c MATCH (e:Equipment {equipment_id:'EQP01'}) MERGE (c)-[:PART_OF {relation_id:'REL-100c4c642c9c9a3c71e6'}]->(e);
MERGE (e:Equipment {equipment_id:'EQP02'}) SET e.area='Photo', e.model_code='PH-9000' WITH e MATCH (m:EquipmentModel {model_code:'PH-9000'}) MERGE (e)-[:OF_MODEL {relation_id:'REL-b955c2f7dc7610f77b1c'}]->(m);
MATCH (e:Equipment {equipment_id:'EQP02'}),(s:ProcessStep {step_id:'CT-PHOTO'}) MERGE (e)-[:PERFORMS {relation_id:'REL-4917f8d0b16db73f13dd'}]->(s);
MERGE (c:Chamber {chamber_id:'EQP02-PM1'}) WITH c MATCH (e:Equipment {equipment_id:'EQP02'}) MERGE (c)-[:PART_OF {relation_id:'REL-bf51ac6003db9dc48a7e'}]->(e);
MERGE (c:Chamber {chamber_id:'EQP02-PM2'}) WITH c MATCH (e:Equipment {equipment_id:'EQP02'}) MERGE (c)-[:PART_OF {relation_id:'REL-152c93b5caa63b1cd673'}]->(e);
MERGE (e:Equipment {equipment_id:'EQP03'}) SET e.area='Photo', e.model_code='PH-9000' WITH e MATCH (m:EquipmentModel {model_code:'PH-9000'}) MERGE (e)-[:OF_MODEL {relation_id:'REL-c76b958937839c683ac8'}]->(m);
MATCH (e:Equipment {equipment_id:'EQP03'}),(s:ProcessStep {step_id:'CT-PHOTO'}) MERGE (e)-[:PERFORMS {relation_id:'REL-fad3c6bdf3a4cfa99394'}]->(s);
MERGE (c:Chamber {chamber_id:'EQP03-PM1'}) WITH c MATCH (e:Equipment {equipment_id:'EQP03'}) MERGE (c)-[:PART_OF {relation_id:'REL-a94cd01da7598b5301ea'}]->(e);
MERGE (c:Chamber {chamber_id:'EQP03-PM2'}) WITH c MATCH (e:Equipment {equipment_id:'EQP03'}) MERGE (c)-[:PART_OF {relation_id:'REL-cc5378c1d70eecbcd620'}]->(e);
MERGE (e:Equipment {equipment_id:'EQP04'}) SET e.area='Etch', e.model_code='ET-7500' WITH e MATCH (m:EquipmentModel {model_code:'ET-7500'}) MERGE (e)-[:OF_MODEL {relation_id:'REL-934819b568952b292a8d'}]->(m);
MATCH (e:Equipment {equipment_id:'EQP04'}),(s:ProcessStep {step_id:'CT-ETCH'}) MERGE (e)-[:PERFORMS {relation_id:'REL-e38c7f27e06c8899ef13'}]->(s);
MERGE (c:Chamber {chamber_id:'EQP04-PM1'}) WITH c MATCH (e:Equipment {equipment_id:'EQP04'}) MERGE (c)-[:PART_OF {relation_id:'REL-9db6aad5f44501c88343'}]->(e);
MERGE (c:Chamber {chamber_id:'EQP04-PM2'}) WITH c MATCH (e:Equipment {equipment_id:'EQP04'}) MERGE (c)-[:PART_OF {relation_id:'REL-ba3911f0f9d34baa7806'}]->(e);
MERGE (e:Equipment {equipment_id:'EQP05'}) SET e.area='Etch', e.model_code='ET-7500' WITH e MATCH (m:EquipmentModel {model_code:'ET-7500'}) MERGE (e)-[:OF_MODEL {relation_id:'REL-f22e6c6ab91265ea23d7'}]->(m);
MATCH (e:Equipment {equipment_id:'EQP05'}),(s:ProcessStep {step_id:'CT-ETCH'}) MERGE (e)-[:PERFORMS {relation_id:'REL-ebf47e0378d72d231233'}]->(s);
MERGE (c:Chamber {chamber_id:'EQP05-PM1'}) WITH c MATCH (e:Equipment {equipment_id:'EQP05'}) MERGE (c)-[:PART_OF {relation_id:'REL-e43225058a9509612a94'}]->(e);
MERGE (c:Chamber {chamber_id:'EQP05-PM2'}) WITH c MATCH (e:Equipment {equipment_id:'EQP05'}) MERGE (c)-[:PART_OF {relation_id:'REL-57e1ba8c7c982ef1ad3b'}]->(e);
MERGE (e:Equipment {equipment_id:'EQP06'}) SET e.area='Etch', e.model_code='ET-7500' WITH e MATCH (m:EquipmentModel {model_code:'ET-7500'}) MERGE (e)-[:OF_MODEL {relation_id:'REL-0cde5cc5e108ac9f2c51'}]->(m);
MATCH (e:Equipment {equipment_id:'EQP06'}),(s:ProcessStep {step_id:'CT-ETCH'}) MERGE (e)-[:PERFORMS {relation_id:'REL-1b06a80e3c5f6c89245c'}]->(s);
MERGE (c:Chamber {chamber_id:'EQP06-PM1'}) WITH c MATCH (e:Equipment {equipment_id:'EQP06'}) MERGE (c)-[:PART_OF {relation_id:'REL-7622ae6c943c9b1c9405'}]->(e);
MERGE (c:Chamber {chamber_id:'EQP06-PM2'}) WITH c MATCH (e:Equipment {equipment_id:'EQP06'}) MERGE (c)-[:PART_OF {relation_id:'REL-707ca87bbd255a0d1864'}]->(e);
MERGE (:Parameter {parameter_id:'PH_DOSE'});
MATCH (s:Parameter {parameter_id:'PH_DOSE'}),(c:Chamber {chamber_id:'EQP01-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-d2de931b285063c7a8ef'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DOSE'}),(c:Chamber {chamber_id:'EQP01-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-6e7de31d637fa88e7498'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DOSE'}),(c:Chamber {chamber_id:'EQP02-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-94cb31fbfc192b9abdae'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DOSE'}),(c:Chamber {chamber_id:'EQP02-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-097b9ff5288f5403b37f'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DOSE'}),(c:Chamber {chamber_id:'EQP03-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-4067eaaf9bcdda275c0c'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DOSE'}),(c:Chamber {chamber_id:'EQP03-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-ade0ca9519682c2cff86'}]->(c);
MERGE (:Parameter {parameter_id:'PH_FOCUS'});
MATCH (s:Parameter {parameter_id:'PH_FOCUS'}),(c:Chamber {chamber_id:'EQP01-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-9687560b5876022b2512'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_FOCUS'}),(c:Chamber {chamber_id:'EQP01-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-a61270e1bcd9464e14dc'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_FOCUS'}),(c:Chamber {chamber_id:'EQP02-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-91aefb741181ce79ea71'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_FOCUS'}),(c:Chamber {chamber_id:'EQP02-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-cc9e336542d29eb098a2'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_FOCUS'}),(c:Chamber {chamber_id:'EQP03-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-7bbfd0a466b4c225ed66'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_FOCUS'}),(c:Chamber {chamber_id:'EQP03-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-c72cf06c3bfd79b7c6e2'}]->(c);
MERGE (:Parameter {parameter_id:'PH_PEB'});
MATCH (s:Parameter {parameter_id:'PH_PEB'}),(c:Chamber {chamber_id:'EQP01-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-75e65f542c456ff70886'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_PEB'}),(c:Chamber {chamber_id:'EQP01-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-c62e80a1d6b485e3373b'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_PEB'}),(c:Chamber {chamber_id:'EQP02-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-bb237f09de82634a44eb'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_PEB'}),(c:Chamber {chamber_id:'EQP02-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-b959daffbf91f6c07c79'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_PEB'}),(c:Chamber {chamber_id:'EQP03-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-f858f8892cdfea6330cf'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_PEB'}),(c:Chamber {chamber_id:'EQP03-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-b48157e4141db07f76c1'}]->(c);
MERGE (:Parameter {parameter_id:'PH_DEV'});
MATCH (s:Parameter {parameter_id:'PH_DEV'}),(c:Chamber {chamber_id:'EQP01-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-47fcae63de255c114f5d'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DEV'}),(c:Chamber {chamber_id:'EQP01-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-8f22fe3c680938465c10'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DEV'}),(c:Chamber {chamber_id:'EQP02-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-e4a0ab6fe192ce3465d5'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DEV'}),(c:Chamber {chamber_id:'EQP02-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-0847973570cbee62a549'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DEV'}),(c:Chamber {chamber_id:'EQP03-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-27062d3fd47ce2a1d74b'}]->(c);
MATCH (s:Parameter {parameter_id:'PH_DEV'}),(c:Chamber {chamber_id:'EQP03-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-572adb9a98d7ab0ca158'}]->(c);
MERGE (:Parameter {parameter_id:'ET_PRES'});
MATCH (s:Parameter {parameter_id:'ET_PRES'}),(c:Chamber {chamber_id:'EQP04-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-421e0a435554181a8191'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_PRES'}),(c:Chamber {chamber_id:'EQP04-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-0876f571789c2b442cbb'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_PRES'}),(c:Chamber {chamber_id:'EQP05-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-5be970ffed253b53d1b7'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_PRES'}),(c:Chamber {chamber_id:'EQP05-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-52c2c8784f19614cc4f5'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_PRES'}),(c:Chamber {chamber_id:'EQP06-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-0f2a39d41e1fd3362b8a'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_PRES'}),(c:Chamber {chamber_id:'EQP06-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-1150b422d370bfc429f0'}]->(c);
MERGE (:Parameter {parameter_id:'ET_REFL'});
MATCH (s:Parameter {parameter_id:'ET_REFL'}),(c:Chamber {chamber_id:'EQP04-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-ed8bc2b436e5549ee896'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_REFL'}),(c:Chamber {chamber_id:'EQP04-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-a0919bc6c40340a831d0'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_REFL'}),(c:Chamber {chamber_id:'EQP05-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-fc856ac7aede1d8f79f0'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_REFL'}),(c:Chamber {chamber_id:'EQP05-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-6ffcfdfd8890401a70d2'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_REFL'}),(c:Chamber {chamber_id:'EQP06-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-b4b039c7e132449cb328'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_REFL'}),(c:Chamber {chamber_id:'EQP06-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-869bcbe9c20500f0454f'}]->(c);
MERGE (:Parameter {parameter_id:'ET_CF4'});
MATCH (s:Parameter {parameter_id:'ET_CF4'}),(c:Chamber {chamber_id:'EQP04-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-fdd5c49f9a018bc958e1'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_CF4'}),(c:Chamber {chamber_id:'EQP04-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-c9fe847bbbd5a611177c'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_CF4'}),(c:Chamber {chamber_id:'EQP05-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-56ad68f33421ffd8d7f2'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_CF4'}),(c:Chamber {chamber_id:'EQP05-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-ae6d1e25f97b96122e12'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_CF4'}),(c:Chamber {chamber_id:'EQP06-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-6e930a8b5640ec575ed0'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_CF4'}),(c:Chamber {chamber_id:'EQP06-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-cbd35525cc666d73b861'}]->(c);
MERGE (:Parameter {parameter_id:'ET_ESC'});
MATCH (s:Parameter {parameter_id:'ET_ESC'}),(c:Chamber {chamber_id:'EQP04-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-bc29e701690f0e2f8cba'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_ESC'}),(c:Chamber {chamber_id:'EQP04-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-590e5df69fed2fa868dd'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_ESC'}),(c:Chamber {chamber_id:'EQP05-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-004232c5b65a02f6491e'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_ESC'}),(c:Chamber {chamber_id:'EQP05-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-f2346673a8beab478589'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_ESC'}),(c:Chamber {chamber_id:'EQP06-PM1'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-5c99a75e427dd1ebb3cf'}]->(c);
MATCH (s:Parameter {parameter_id:'ET_ESC'}),(c:Chamber {chamber_id:'EQP06-PM2'}) MERGE (s)-[:MEASURED_ON {relation_id:'REL-4f818b9f223deb1f5b5b'}]->(c);
